name = "CEGISPolyhedralLyapunov"
uuid = "971fcdcf-521e-48aa-b645-6a6e748d6844"
authors = ["guberger <guillaume.berger@colorado.edu>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
